### ISSUE TITLE
Not well optimized in terms of responsiveness on mobile 

### ISSUE THREAD

**Issue by Jonnie-Dev** [subhoghoshX/laureate#10]
The tweet image fills the whole viewport width which doesn't look like a good practice, a lil margin on the sides should fix this and I think it'll look great with that too.

**Comment by NimperX** [comment]
May I work on this issue?

**Comment by subhoghoshX** [comment]
> I can optimize this, should i?

I can see there's already a PR linked to this issue.

I was thinking of solving it another way. You guys should always discuss before working on a PR.

**Comment by shouryakhanka** [comment]
How you wanted it to be, we can discuss

**Comment by NimperX** [comment]
Hi @shouryakhanka , Can you elaborate more on the above statement? What did you mean by optimizing?

**Comment by subhoghoshX** [comment]
The card looks good for now, thanks to @NimperX work.
