### ISSUE TITLE
Add husky and commit lint for consistent and bug-free commits

### ISSUE THREAD

**Issue by vedantnn71** [subhoghoshX/laureate#12]

**Comment by subhoghoshX** [comment]
Sounds good. Feel free to send a PR if you want.

**Comment by vedantnn71** [comment]
Sure. My pr is on the way :)

**Comment by vedantnn71** [comment]
Done ✅ 

I'll create two PRs for husky and commitlint after the merge of #11

**Comment by vedantnn71** [comment]
#28

**Comment by subhoghoshX** [comment]
> #28

Write `Closes #28` in the PR description. It'll automatically link it to the issue and also close the issue when the PR is merged.
