### ISSUE TITLE
[FEATURE] Add dark mode

### ISSUE THREAD

**Issue by subhoghoshX** [subhoghoshX/laureate#2]
Add dark mode. Here's the design with color codes.

![laureate-dark](https://user-images.githubusercontent.com/108616679/192949660-2495db81-4006-4019-9178-b88b0519ebe4.png)

**Comment by Rounak-28** [comment]
Hey @subhoghoshX
Can I work on this?

**Comment by codewithnadeem14502** [comment]
hello sir , i would love to work on  this issue

**Comment by subhoghoshX** [comment]
Hey, @codewithnadeem14502 thanks for showing interest in the project. I think @Rounak-28 should get the chance to work on it as he commented first.

Let's see if @Rounak-28 is still available.

Also, feel free to revisit the issues later. I'm planning to create a few.

**Comment by Rounak-28** [comment]
@subhoghoshX should I start to work in these?
