### ISSUE TITLE
[BUG] Sidebar displays negative values after resizing the image

### ISSUE THREAD

**Issue by tryonelove** [subhoghoshX/laureate#31]
When resizing image, it's allowed to resize it down to negative value (according to the sidebar). When resizing the image back, sidebar says it's still a negative value, despite image being resized normally.
![image](https://user-images.githubusercontent.com/20541870/193640895-f2b1b977-9d71-4fcf-9622-31e2562b69ea.png)

**Comment by ShaneMaglangit** [comment]
Can I be assigned on this? Would love to work on it.

**Comment by subhoghoshX** [comment]
No, it's not fixed yet. You just need to set a minimum value (maybe 0) for those variables. Feel free to work on it if you want. You should change the store files, specifically the actions.

**Comment by tryonelove** [comment]
OK, I'll work on that.
