### ISSUE TITLE
[FEAT] Trigger a message when file is copied/downloaded

### ISSUE THREAD

**Issue by Coding-Hashira** [subhoghoshX/laureate#32]
## Problem

Currently, whenever user clicks on save or copy button, nothing happens on the completion of the task. For save button, you know if it worked or not as you'll see a new file downloading, but for copy button, you've no idea even if it's working or not!

## Solution
We can add a success message (maybe in the form of a toast) whenever user downloads or copies an image. Maybe we can use a package for that such as [React-Toastify](https://www.npmjs.com/package/react-toastify) for that.

Also, I'd love to work on this issue!

**Comment by subhoghoshX** [comment]
Hey, thanks. I think you can just change the copy icon to show that it is copied, no need to be fancy.

Feel free to work on it. It'd be better if we first come up with an appropriate icon to show when it is copied.

**Comment by Coding-Hashira** [comment]
> Hey, thanks. I think you can just change the copy icon to show that it is copied, no need to be fancy.
> 
> Feel free to work on it. It'd be better if we first come up with an appropriate icon to show when it is copied.

Yea, we can do that! Let me find an icon!

You don't want to use a package even for icons?

**Comment by Coding-Hashira** [comment]
Got your point! I think a normal check icon will look fine for this purpose.

BTW, I'd be okay if someone else wants to work on this issue!

**Comment by jalezi** [comment]
@subhoghoshX you can assign me.
