### ISSUE TITLE
Broken link in README as the Discussions section is not enabled for the repository.

### ISSUE THREAD

**Issue by Karthik-315** [subhoghoshX/laureate#35]
## Problem
The [feature request](https://github.com/subhoghoshX/laureate/discussions/new) link in the [README](https://github.com/subhoghoshX/laureate/blob/main/README.md) file seems to be not working as the **Discussions** tab is not enabled.

## Solution
@subhoghoshX, enable the discussions tab, so that contributors can request/suggest new features.
This [link](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/enabling-or-disabling-github-discussions-for-a-repository) may help with the same. Let me know if I can help in any way

**Comment by subhoghoshX** [comment]
Done. Enabled it. The `Discussions` tab was visible to me, so I thought it was enabled. Thanks, @Karthik-315.
