### ISSUE TITLE
KeyboardEvent.keyCode is deprecated

### ISSUE THREAD

**Issue by jalezi** [subhoghoshX/laureate#36]
### Description

In `<Input/>` in `keyDownHandler` we are using `e.keyCode` which is, according to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode), deprecated.

### Solution

Use KeyboardEvent.code.

```javascript
  const KEYBOARD_CODES = {
    ARROW_UP: "ArrowUp", // keyCode = 38
    ARROW_DOWN: "ArrowDown", // keyCode = 40
    ENTER: "Enter", // keyCode = 13
  };

  function keyDownHandler(e: any) {
    if (e.code === KEYBOARD_CODES.ARROW_UP) {
      setData(() => +dimensionBuffer + 1);
    } else if (e.code === KEYBOARD_CODES.ARROW_DOWN) {
      setData(() => +dimensionBuffer - 1);
    } else if (e.code === KEYBOARD_CODES.ENTER) {
      if (Number.isNaN(Number(dimensionBuffer))) {
        setDimensionBuffer(data + "");
      } else {
        setData(() => +dimensionBuffer);
      }
    }
  }
```

**Comment by jalezi** [comment]
@subhoghoshX you can assign me and I can fix also #37

**Comment by subhoghoshX** [comment]
Yeah I know it's deprecated, but one good thing about the web is that deprecated doesn't mean it'll soon be removed hehe.

You can work on it if you want. No need to create a separate object, just put the key name in the conditions.

**Comment by jalezi** [comment]
Do you care about nested `if..else..if`? `switch` is maybe more readable.

**Comment by subhoghoshX** [comment]
Yeah, feel free to use `switch`.
