### ISSUE TITLE
[BUG] Profile image does not load in firefox

### ISSUE THREAD

**Issue by zelfroster** [subhoghoshX/laureate#43]
### Twitter profile image is not loading in Firefox
![1665078954_Oct06_23:25:54](https://user-images.githubusercontent.com/93514460/194386065-6e781a51-06bf-48d2-ba5b-facc6e0ba0bc.png)

**Comment by subhoghoshX** [comment]
Interesting, I'm using the Linux build of Firefox and I guess @zelfroster is also using the Linux build.

> Also, @subhoghoshX, we may need a generic Alt text for the profile image.

Good catch. I'll fix it right away after I merge the dark feature branch.

**Comment by zelfroster** [comment]
Yup And also, I am using Librewolf (a fork or firefox).

**Comment by jalezi** [comment]
> Good catch. I'll fix it right away after I merge the dark feature branch.

@subhoghoshX and use next/future/image?

**Comment by subhoghoshX** [comment]
> @subhoghoshX and use next/future/image?

I tried next/image, it doesn't work. And it shouldn't I guess. It's more of a browser issue, the linux version of firefox to be specific as it work on @Karthik-315's firefox.

**Comment by subhoghoshX** [comment]
**Update:**

I discovered that it's firefox that's blocking the image because it's from Twitter, firefox thinks of it as some kind of tracker.

If you click on the shield icon in the bookmark bar and turn off **Enhanced Tracking Protection** the image starts showing.

**Comment by zelfroster** [comment]
Ahhh… Nice dude… You finally found the culprit.
So, Should I close this issue?
If there is a fix for it, then great, or else you will have to mention it in the docs.

**Comment by subhoghoshX** [comment]
Fixed it with this [commit](https://github.com/subhoghoshX/laureate/commit/bbdd336750f388214e93ec21523eec17da68a73c).
