### ISSUE TITLE
[FEAUTURE] Improve exported image resolution

### ISSUE THREAD

**Issue by subhoghoshX** [subhoghoshX/laureate#5]
The image exported from the app at the moment has the same resolution as it appears on the screen. It'd be nice if it export 2-3 times the resolution.

[ExportButton.tsx](https://github.com/subhoghoshX/laureate/blob/main/components/ExportButton.tsx) is the file you should work on specifically the `exportPNG()` function. Figure out a way to convert the canvas image to a higher resolution.

**Comment by dhrumishah** [comment]
> Sure, that'd be great.

Can you explain me a bit more about the issue? (it would be great if you can share screenshot)

**Comment by subhoghoshX** [comment]
Yeah sure. Just visit https://laureate.netlify.app, click on the download button at bottom-left, and have look at the exported image.

Maybe try to zoom in to see that the quality/resolution of the image isn't good enough.

[This](https://github.com/subhoghoshX/laureate/blob/main/components/ExportButton.tsx#L10) is where the canvas is being transformed into the image.

The task is to do some research on _how to convert a canvas to an image_ in a way that the exported image's resolution is higher. And implement it.

P.S. It'd be best if you can do it without a library, should be simple enough.

**Comment by dhrumishah** [comment]
Okay got that :)

> Yeah sure. Just visit https://laureate.netlify.app, click on the download button at bottom-left, and have look at the exported image.
> 
> Maybe try to zoom in to see that the quality/resolution of the image isn't good enough.
> 
> [This](https://github.com/subhoghoshX/laureate/blob/main/components/ExportButton.tsx#L10) is where the canvas is being transformed into the image.
> 
> The task is to do some research on _how to convert a canvas to an image_ in a way that the exported image's resolution is higher. And implement it.
> 
> P.S. It'd be best if you can do it without a library, should be simple enough.


Okay got that :)

**Comment by dhrumishah** [comment]
Hey @subhoghoshX, I checked out some libraries too, but none of them helps in increasing the resolution. It just helps to resize the image.

**Comment by subhoghoshX** [comment]
Hey @dhrumishah, it turned out to be much simpler :laughing: You just have to add the `scale` key to the options object that is passed to the `html2canvas` function [here](https://github.com/subhoghoshX/laureate/blob/main/components/ExportButton.tsx#L6).

Sorry for the trouble. Hopefully, you learned something about Canvas.

I think a scale value of 3 is good enough.

As this issue turned out to be much simpler (only have to add one line), if you want you can make the download button a little better.

Here's a quick demo I made in figma of what I've been thinking of:

https://user-images.githubusercontent.com/108616679/193262999-33c13fbb-05c0-41a7-bb4c-a4442675a536.mp4

And yes it is inspired by the dynamic island thing :laughing: You can add some fancy bouncy or springy animation or whatever you want.

Let me know you'd like to work on it.

**Comment by dhrumishah** [comment]
Ah well! Let me just do this 😂

For the download button can we create different issue! I would really like to work on that :)

**Comment by dhrumishah** [comment]
> Ah well! Let me just do this 😂
> 
> For the download button can we create different issue! I would really like to work on that :)



> 



> Hey @dhrumishah, it turned out to be much simpler 😆 You just have to add the `scale` key to the options object that is passed to the `html2canvas` function [here](https://github.com/subhoghoshX/laureate/blob/main/components/ExportButton.tsx#L6).
> 
> Sorry for the trouble. Hopefully, you learned something about Canvas.
> 
> I think a scale value of 3 is good enough.
> 
> As this issue turned out to be much simpler (only have to add one line), if you want you can make the download button a little better.
> 
> Here's a quick demo I made in figma of what I've been thinking of:
> 
>  island-download.mp4 
> And yes it is inspired by the dynamic island thing 😆 You can add some fancy bouncy or springy animation or whatever you want.
> 
> Let me know if you'd like to work on it.

I thought I didn't need to scale up the size of the image😂

**Comment by subhoghoshX** [comment]
haha ok. It's the same component anyway.
